config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'admin' => 'pages#admin'
  get 'microsites' => 'microsites#index'
  match '/microsite/create' => 'microsites#create', :as => :create_microsite, via: [:post]
  match '/microsite/destroy' => 'microsites#destroy', :as => :destroy_microsite, via: [:destroy, :post]
  match '/reading/upload' => 'readings#upload', :as => :upload_readings, via: [:post]
  match '/pages/home'=> 'pages#home', via: [:post, :get]
  get 'readings' => 'readings#index'

  devise_for :users, :skip => :registrations

end

app/views/pages/admin.html.erb
<header>
    <h1>Helmuth Lab Database</h1>

    <% if user_signed_in? %>
        <div id="admin-tools">
            
        </div>
        <div id="admin-login" class="logged-in">
            <span id="current-user"><%= link_to(current_user.email, '/') %></span>
            <%= link_to('Log Out', destroy_user_session_path, method: :delete, class: "generic-button") %>
        </div>
    <% else %>
        <div id="admin-login" class="logged-out">
            <%= link_to('Log In', new_user_session_path, class: "generic-button") %>
        </div>
    <% end %>
</header>

<% if user_signed_in? %>
    <div id="create-microsite" class="admin-panel left-column">
        <h3>New Microsite</h3>
        <hr />
        <%= form_for @microsite, url: create_microsite_path, :html => {:class => "form-inline"} do |f| %>
            <p>
            <%= f.label :microsite_id, "Microsite ID" %><br>
            <%= f.text_field :microsite_id, class: 'form-control input-sm' %>
            </p>

            <p>
            <%= f.label :site %><br>
            <%= f.text_field :site, class: 'form-control input-sm' %>
            </p>

            <p>
            <%= f.label :field_lat, "Field Latitude" %><br>
            <%= f.text_field :field_lat, class: 'form-control input-sm' %>
            </p>

            <p>
            <%= f.label :field_lon, "Field Longitude" %><br>
            <%= f.text_field :field_lon, class: 'form-control input-sm' %>
            </p>

            <p>
            <%= f.label :location %><br>
            <%= f.text_field :location, class: 'form-control input-sm' %>
            </p>

            <p>
            <%= f.label :country %><br>
            <%= f.country_select :country, class: 'form-control input-sm' %>
            </p>

            <p>
            <%= f.label :state_province, "State / Province" %><br>
            <%= f.text_field :state_province, class: 'form-control input-sm' %>
            </p>

            <p>
            <%= f.label :biomimic %><br>
            <%= f.select :biomimic, options_for_select(["Barnacle", "Coral", "Mussel", "Sea Star"], class: 'form-control input-sm') %>
            </p>

            <p>
            <%= f.label :zone %><br>
            <%= f.text_field :zone, class: 'form-control input-sm' %>
            </p>

            <p>
            <%= f.label :sub_zone, "Sub-Zone" %><br>
            <%= f.select :sub_zone, options_for_select(["Backreef", "Forereef", "High", "High Mid", "Lagoon", "Low", "Low Mid", "Mid", "Terr"], class: 'form-control input-sm')  %>
            </p>

            <p>
            <%= f.label :wave_exp, "Wave Exposure" %><br>
            <%= f.select :wave_exp, options_for_select(["Exposed", "Intermediate", "Moderately Exposed", "Protected"], class: 'form-control input-sm') %>
            </p>

            <p>
            <%= f.label :tide_height, "Tide Height" %><br>
            <%= f.text_field :tide_height, class: 'form-control input-sm' %>
            </p>

            <p>
            <%= f.submit "Create Microsite", class: "btn btn-success btn-md" %>
            </p>
        <% end %>
    </div>
    <div class="right-column">
        <div id="destroy-microsite" class="admin-panel">
            <h3>Delete Microsite</h3>
            <hr />
            <%= form_for(:microsite, url: destroy_microsite_path, html: { multipart: true }) do |f| %>
                <p>
                    <%= f.label :microsite_id, "Microsite ID" %><br>
                    <%= f.select :id, options_for_select(Microsite.all.collect {|m| [m.microsite_id, m.id]}.sort) %>
                </p>
                <%= f.submit "Destroy Microsite", class: "btn btn-danger btn-md" %>
            <% end %>
        </div>
        <div id="upload-readings" class="admin-panel">
            <h3>Upload Readings</h3>
            <hr />
            <%= form_for(:reading, url: upload_readings_path, html: { multipart: true }) do |f| %>
                <p>
                    <%= f.label :microsite_id, "Microsite ID" %><br>
                    <%= select_tag :microsite_id, options_for_select(Microsite.all.collect {|m| [m.microsite_id, m.id]}.sort) %>
                </p>
                <p>
                    <%= f.label :date_format, "Date Format" %><br>
                    <%= select_tag :date_format, options_for_select(["DayMonthYear", "MonthDayYear", "YearMonthDay"]) %>
                </p>
                <p>
                    <%= file_field(:file, :data, accept: "text/plain") %>
                </p>
                <%= submit_tag "Upload Text File", class: "btn btn-success btn-md" %>
            <% end %>
        </div>
    </div>
<% else %>
    <h3>Please login to access admin tools</h3>
<% end %>

app/views/pages/home.html.erb
<header>
    <h1>Helmuth Lab Database</h1>

    <% if user_signed_in? %>
        <div id="admin-login" class="logged-in">
            <span id="current-user"><%= link_to(current_user.email, '/admin') %></span>
            <%= link_to('Log Out', destroy_user_session_path, method: :delete, class: "generic-button") %>
        </div>
    <% else %>
        <div id="admin-login" class="logged-out">
            <%= link_to('Log In', new_user_session_path, class: "generic-button") %>
        </div>
    <% end %>
</header>

<%= form_for @search, :url => "/pages/home", :html => {:id => "main-search", :class => "form-inline main-search"} do |f| %>
    <div class="form-group">
        <%= f.label 'Site' %>
        <%= f.text_field 'site', placeholder: "Site", class: 'form-control input-sm' %>
    </div>
    <div class="form-group">
        <%= f.label 'State/Province', "State / Province" %>
        <%= f.text_field 'state_province', placeholder: "State / Province", class: 'form-control input-sm' %>
    </div>
    <div class="form-group">
        <%= f.label 'Country' %>
        <%= f.select :country, @country, {:prompt => "Country"}, {:multiple => true, :class => "select", :id => "country"} %><br>
    </div>
    <div class="form-group">
        <%= f.label 'Zone' %>
        <%= f.text_field :zone, placeholder: "Zone", class: 'form-control input-sm' %>
    </div>
    <div class="form-group">
        <%= f.label :sub_zone, "Sub-Zone" %>
        <%= f.select :sub_zone, @sub_zone, {:prompt => "SubZone"}, {:multiple => true, :class => "select", :id => "sub_zone"} %><br>
    </div>
    <div class="form-group">
        <%= f.label 'Biomimic' %>
        <%= f.select :biomimic, @biomimic, {:prompt => "Biomimic"}, {:multiple => true, :class => "select", :id => "biomimic"} %><br>
    </div>
    <div class="form-group">
        <%= f.label :wave_exp, "Wave Exposure" %>
        <%= f.select :wave_exp, @wave_exp, {:prompt => "Wave Exposure"}, {:multiple => true, :class => "select", :id => "wave_exp"} %><br>
    </div><br>
    <%= f.submit "Search", class: "btn btn-default btn-md main-search-submit"%>
    <%= link_to('Export CSV', '#', class: "btn btn-default btn-md main-search-submit", onclick: "updateFilter(this)")%>
<% end %>

<div id="map" data-microsites="<%= @hash.to_json %>"></div>

<%= line_chart Microsite.all.first(10).collect { |m|
    {name: m.id, data: Reading.where(microsite_id: m.id).collect { |r|
        [r.timestamp, r.temperature]
    }}
},
id: "temp-graph",
library: {
    chart: {
        panning: true,
        panKey: 'shift',
        zoomType: "x"
    },
    tooltip: {valueSuffix: "º"},
    yAxis: {
        title: {text: "Temperature (C)"},
        labels: {format: "{value}º"}
    }
}%>